### ISSUE TITLE
Slf4jAccessLogReceiver

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [StubbornJava/StubbornJava#103]
it's better to use explicit constant message format:
use `logger.info("{}", message)` instead of `logger.info(message)`.
see https://github.com/KengoTODA/findbugs-slf4j, SLF4J_FORMAT_SHOULD_BE_CONST

**Comment by billoneil** [comment]
I don't think that matters when you are only passing a String in with no other template. It's not going to hit the optimization where it doesn't call toString.

**Comment by whyicantusemyemailasusername** [comment]
I think the rule is here because first parameter is always parsed as template. If template is a constant string, it can be cached. Otherwise it got parsed every call.
