### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.getSerializerProviderInstance()

### ISSUE THREAD

**Issue by yuanmei-norra** [StubbornJava/StubbornJava#105]
SerializerProvider serializers = mapper.getSerializerProviderInstance();

In DeterministicObjectMapper class, above line will throw NoSuchMethodError.

**Comment by billoneil** [comment]
It appears like that method was removed in a newer jackson version I would need to look into the new way to handle this. From a quick look you might be able to extend `ObjectMapper` and call https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L2235
