### ISSUE TITLE
Cannot build root project with dependencies with one gradle command

### ISSUE THREAD

**Issue by volyx** [StubbornJava/StubbornJava#40]
Cannot find project stubbornjava-private

**Comment by billoneil** [comment]
I need to think about how to fix this, I'm no gradle expert. There are some files in a private repo I'll see if I can make them public or figure out how to remove them from the default build.

**Comment by volyx** [comment]
Thx!

**Comment by billoneil** [comment]
Are you able to work around this for now? I definitely want to fix it just need to figure out a reasonable way to reconfigure my deployments.

**Comment by volyx** [comment]
I did quick workaround  https://github.com/volyx/test-undertow - just put everything that I need in one one package :)
