### ISSUE TITLE
Serving static files from resources folder

### ISSUE THREAD

**Issue by sachin-walia** [StubbornJava/StubbornJava#71]
Wondering if you may help how to use undertow for serving static files (html, css, js, png) along with APIs. I am trying to serve swagger-ui assets from resources along with APIs. Thanks in advance.

**Comment by billoneil** [comment]
You can find a resource handler here https://github.com/StubbornJava/StubbornJava/blob/master/stubbornjava-common/src/main/java/com/stubbornjava/common/undertow/handlers/CustomHandlers.java#L68 that can serve files from both local disk or from the jar. 

https://www.stubbornjava.com/posts/webpack-and-npm-for-simple-java-8-web-apps briefly shows how it can be used. You might want to customize it yourself a bit this one is a little coupled to the config currently.
