### ISSUE TITLE
How to create an Integration Test with this project?

### ISSUE THREAD

**Issue by jabrena** [StubbornJava/StubbornJava#78]
Hi I would like to test and API created with this project but I don´t find a way to stop the server after every test.

``` java
SimpleServer server = SimpleServer.simpleServer(Middleware.common(ROOT));
server.start();
```

Can you help me?

Juan Antonio

**Comment by jabrena** [comment]
Test Example:

``` java
import io.restassured.RestAssured;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static io.restassured.RestAssured.when;

public class IntegrationTest {

    private final static int DEFAULT_PORT = 8080;
    private final static String DEFAULT_HOST = "http://localhost/";

    private APIServer server;

    @Before
    public void setup() {
        RestAssured.baseURI = DEFAULT_HOST;
        RestAssured.port = DEFAULT_PORT;
        server = new APIServer();
    }

    @After
    public void after() {
        server.stop();
    }

    @Test
    public void whenRequestGetNavigatorPose_thenOK(){
        when().request("GET", "/api/robot/navigator/pose")
              .then().statusCode(200);
    }

}
```

**Comment by billoneil** [comment]
Just pushed https://github.com/StubbornJava/StubbornJava/commit/05f411765a0edff7df1d0bc4d82164e0660c5f76 which will return the Undertow instance when you call start(). This will allow you to stop the server in your test case.

I will keep this open for now because a better way to test that manages the ports for you would be beneficial.

**Comment by billoneil** [comment]
Somewhat related https://issues.jboss.org/browse/UNDERTOW-628. If you pass 0 as the port Undertow will pick a random open port for you which you can get from the listener config.

**Comment by billoneil** [comment]
Sorry for the long delay I recently added a helper for this. It will take an `Undertow.Builder`, `HttpHandler`, and a `Consumer<String>`. The consumer will get passed the hostname it is listening on including the random port Undertow assigned.

https://github.com/StubbornJava/StubbornJava/blob/master/stubbornjava-common/src/main/java/com/stubbornjava/common/undertow/UndertowUtil.java#L29

You can see it being used here https://github.com/StubbornJava/StubbornJava/blob/master/stubbornjava-common/src/test/java/com/stubbornjava/common/undertow/handlers/diagnostic/DelayedExecutionHandlerTest.java#L72
