### ISSUE TITLE
Rss feed?

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [StubbornJava/StubbornJava#97]
I'd love to subscribe for updates on https://www.stubbornjava.com/ via RSS

**Comment by billoneil** [comment]
I haven't used RSS before so let me know if this doesn't work. https://www.stubbornjava.com/rss/feed

**Comment by billoneil** [comment]
cc @robotmlg

**Comment by whyicantusemyemailasusername** [comment]
Thanks, /rss/feed link work great. It may be worth adding rss autodiscovery via meta tags: http://www.rssboard.org/rss-autodiscovery or <a> tag: https://developer.mozilla.org/en-US/docs/Archive/RSS/Getting_Started/Syndicating

Thanks again for the fast turnaround!

**Comment by billoneil** [comment]
I think this should do it https://github.com/StubbornJava/StubbornJava/pull/99.

**Comment by whyicantusemyemailasusername** [comment]
Great! W3C validator says that the feed is valid with minor warnings:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.stubbornjava.com%2F
